# Add configuration values here, as shown below.
#

# FOR MAILGUN CONFIG
MAILGUN_DOMAIN: JustAnExample
MAILGUN_SMTP_LOGIN: JustAnExample
MAILGUN_SMTP_PASSWORD: JustAnExample
MAILGUN_SMTP_PORT: JustAnExample
MAILGUN_SMTP_SERVER: JustAnExample